### ISSUE TITLE
Astra H CAN database

### ISSUE THREAD

**Issue by obertr0n** [megadrifter/Astra-H#1]
Hello, would you be so kind to share your CAN database, or CAN IDs that you discovered your tests?
Thank you in advance.

**Comment by megadrifter** [comment]
Hi. Yet not so much. 
First I took MS CAN IDs here https://sites.google.com/site/astracarpc/ms-can
Others are still only in paper. 
Also You can find something in the #define section of the file https://github.com/megadrifter/Astra-H/blob/master/MS-module/MS-module.ino
Hope this helps a bit. 
How do you think, will it make sense to create special library to store these "defines" in a separate file?

**Comment by megadrifter** [comment]
Hi! There are some in the #define section of the MS-Module.ino

**Comment by obertr0n** [comment]
Hello and thank you for you reply. I will give it a look and see what I can use.
Regarding the defines, I think for now are ok to be bulked together since, from what I understand the project is still ongoing, but what you get closer to the end I think would be a great idea to cleanup some code :).
Anyway, nice work you did!

**Comment by obertr0n** [comment]
Hello again, I started to look at the STM32F103 devboard since the AtMega328 is starting to become useless for me. Could you please help me with the transceiver that you used? Thank you!

**Comment by megadrifter** [comment]
Hi! Sure!
First, you can rad my artticle (in native language) at https://www.drive2.ru/l/485801071864709696/

So, it is MCP2551. Or could be TJA1060 as on the popular can shield with mcp2515.

**Comment by megadrifter** [comment]
Final place for database will be 
https://github.com/Trueffelwurm/Car-CAN-Message-DB/tree/master/Opel/Astra/H
and my fork https://github.com/megadrifter/Car-CAN-Message-DB/tree/master/Opel/Astra/H
